INSERT INTO role (role_id, role_name) VALUES (1, 'ROLE_USER')
INSERT INTO role (role_id, role_name) VALUES (2, 'ROLE_ADMIN')
INSERT INTO user (user_id, username,first_name, last_name, password) VALUES (1, 'fdherrera@gmail.com','Federico', 'Herrera', '$2a$12$8Dvrv6m66oRavF71G5A72OL.mtjAn1mpeXzp3GJi410nrT5IR9de2')
INSERT INTO user (user_id, username,first_name, last_name, password) VALUES (2, 'otroemail@repiola.com','Pepito', 'Longaniza','$2a$12$8Dvrv6m66oRavF71G5A72OL.mtjAn1mpeXzp3GJi410nrT5IR9de2')
INSERT INTO user_roles VALUES (1,1)
INSERT INTO user_roles VALUES (2,2)
